name: "Github Action for deploy Vue app to AWS S3 bucket 🗑"
description: "Easy way to build and upload distributibles files of Vue application to AWS S3 bucket"

branding:
  icon: "archive"
  color: "orange"

inputs:
  AWS_ACCESS_KEY_ID:
    description: "AWS Access key ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS Secret access key"
    required: true
  AWS_DEFAULT_REGION:
    description: "Bucket region (ex: us-east-1)"
    required: true
  AWS_BUCKET_NAME:
    description: "AWS S3 bucket name"
    required: true
  AWS_CLOUDFRONT_DIST_ID:
    description: "AWS CloudFront Distribution ID"
    required: false
  AWS_INVALIDATION_PATH:
    description: "Aws CloudFront Distribution Invalidation path"
    required: false
  APP_SOURCE_CODE:
    description: "Source files location. Default: root directory."
    required: false
    default: ./
  BUILD_COMMAND:
    description: "Command used to build your application. Ex: `npm run build`"  
    required: false
    default: production

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
    AWS_BUCKET_NAME: ${{ inputs.AWS_BUCKET_NAME }}
    AWS_CLOUDFRONT_DIST_ID: ${{ inputs.AWS_CLOUDFRONT_DIST_ID }}
    AWS_INVALIDATION_PATH: ${{ inputs.AWS_INVALIDATION_PATH }}
    APP_SOURCE_CODE: ${{ inputs.APP_SOURCE_CODE }}
    BUILD_COMMAND: ${{ inputs.BUILD_COMMAND }}
